# Generated by Django 2.1.4 on 2019-01-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('planid', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='主键')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('urladdres', models.CharField(max_length=500, verbose_name='任务地址')),
                ('oprate', models.CharField(max_length=200, verbose_name='执行')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('object_id', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(max_length=100, verbose_name='联系地址')),
                ('message', models.CharField(max_length=500, verbose_name='留言信息')),
            ],
            options={
                'verbose_name': '用户留言信息',
                'verbose_name_plural': '用户留言信息',
            },
        ),
    ]
